### PR TITLE
Add note for main page

### PR DESCRIPTION
**Pull request by jaronheard**
Took a stab at addressing #60 by adding this disclaimer to the top of the page.
 
image

I used a [perma.cc link](https://perma.cc/5QLX-4FG7) to prevent link-rot on the new minimum wage law link I added.

### CODE REVIEW

**Comment by jaronheard** [comment]
@danieljwest @nrbernard @caterinasworld Can one of you review this? Do we need to redeploy once this is merged?

**Comment by danieljwest** [comment]
Sure thing. If my automatic deploy stuff still functions it should auto deploy.... Let's see what happens!

**Comment by danieljwest** [comment]
Looks like this may have failed to deploy and took the site with it. Unfortunately I don't have the keys to the ship anymore. I'm going to revert it, to see if it happens to be a bug in this change (but I can't see how that would happen). I suspect one of our dependencies no longer exists (probably due to that security issue)

**Comment by jaronheard** [comment]
@Raise-Effect/owners Does anyone have the keys to deploy? Would be great to have this back up

**Comment by jaronheard** [comment]
Does anyone have the keys? Cat wanted to take someone on a Raise Effect test drive the other day and it didn't start 😢

Jaron Heard
Creative Director
Civic Software Foundation

+1-971-998-7180

**Pull request merged**
