### PR TITLE
Build branch

### PR DESCRIPTION
**Pull request by florapdx**
This branch adds Backbone infrastructure, build tooling, and instructions for running the app locally. There is very minimal application code here, but you'll find an extensible router and controller and a couple of views (including a "root view" whose job is to register/deregister page views). There's also basic tooling and starter files for building styles in SASS (using node-sass, so no ruby req'd). 

Please read the README to get started.

### CODE REVIEW

**Comment by nrbernard** [comment]
This looks great to me, @florapdx! Thanks for all your hard work.

@jaronheard has the most recent version of the map page on his [presentationTestBranch](https://github.com/Jobs-Economy/test/tree/presentationTestBranch). @jaronheard, is the remote branch up to date with your local version?

@florapdx I'm happy to sort out the merge conflicts once `master` is up to date—whatever's easiest!

**Comment by jaronheard** [comment]
@nrbernard It's up to date, though it's still just a messy illustration. I think when we figure out what we actually want to do with the map I can go through it again and see what we want to keep.

**Comment by nrbernard** [comment]
@jaronheard Ok, if it seems worth it I'll merge it in just so we have something to see with the Backbone app. The map example isn't much code anyway.

What do you think, @florapdx?

**Comment by florapdx** [comment]
@nrbernard Please feel free to pull whatever files into this repo, or I can plug them in this evening. :)

**Comment by nrbernard** [comment]
@florapdx Right on—I'll tackle it this evening. Thanks!

**Comment by nrbernard** [comment]
Ok I've updated the homepage view to display the map with Leaflet. I just threw all the JS into the template—I realize this isn't the best way to do this, but I figure we won't keep most of it and I just want to get something up and running. I also just imported the Leaflet.css in the the `base.scss` file but, again, probably a better way to include that dependency in the future.

If this looks good to you @florapdx and @jaronheard let's merge it!

**Comment by gareth-ferneyhough** [comment]
Hey guys. Simple question: how do I run this locally?

**Comment by nrbernard** [comment]
@gareth-ferneyhough I followed Flora's [README](https://github.com/Jobs-Economy/test/blob/build-branch/README.md) it everything went smoothly for me

**Comment by gareth-ferneyhough** [comment]
Got it. Forgot to look at the other branches.

**Comment by jaronheard** [comment]
@nrbernard looks good to merge to me. @florapdx i'll let you take a look and hit the merge button! :+1:

**Comment by florapdx** [comment]
LGTM! Next step would be to pull the content of this html page out into a template and build a Backbone view for the map code so we can feed in variable data. 

Merging! :ship:

**Pull request merged**
